# Sets and Set Operations

## What is a Set? 

In probability theory, a set is defined as a *well-defined collection of objects*. 

Mathematically, you can denote a set by $S$. If an element $x$ belongs to a set $S$, then you'd write $x \in S$. On the other hand, if $x$ does not belong to a set $S$, then you'd write $x\notin S$.

Example: If $S$ is defined as the set of even numbers, then:

* If $x = 2$, $x\in S$ because $x$ is an even number.

* If $x = 9$, $x\notin S$ because $x$ is not an even number.


## Subsets

Set $T$ is a subset of set $S$ if *every element* in set $T$ is also in set $S$. The mathematical notation for a subset is $T \subseteq S$. 

Typically, you'll be more interested in *proper subsets*. All proper subsets are subsets. The only difference between subsets and proper subsets is that a subset can technically be the entire set. In other words, if A = {1,2,3} and B = {1,2,3} A is subset of B. If C = {1,2} then C is both a subset and proper subset of A. C is also a subset and proper subset of B. The mathematical notation for proper subsets is : $ C \subset A $

**Example**: If S is the set of even numbers, set $T = \{2, 6, 22\}$ is a proper subset of $S$. Formally, you can write this as $T \subset S$. $T \subseteq S$ is also correct in this case!

## Universal Sets

The collection of all possible outcomes in a certain context or universe is called the **universal set**.
A universal set is often denoted by $\Omega$.

Example of a universal set: All the possible outcomes when rolling a dice.

$\Omega = \{1,2,3,4,5,6\}$

Remember that a universal set is not necessarily all the possible things that have ever existed. Typically, a universal set is just all the possible elements within certain bounds, e.g., the set of all countries in the world, the set of all the animal species in the Bronx Zoo, etc.

A universal set can have an infinite number of elements, for example, the set of all real numbers!

## Elementary Set Operations

Next, let's talk about set operations. Imagine you have two sets of numbers, say the first 4 multiples of 3 in set $S$:

$ S = \{3,6,9,12\}$

and the first 4 multiples of 2 in set $T$:

$ T = \{2,4,6,8\} $.

### a) Union of Two Sets

The union of two sets $S$ and $T$ is the set of elements of either S or T, or in both.  

Applied to our example, the union of $S$ and $T$ is given by the elements $\{2,3,4,6,8,9,12\}$. 

In mathematical terms, the union of $S$ and $T$ is denoted as $S \cup T$.

A popular way to represent sets and their relationships is through Venn Diagrams, (https://en.wikipedia.org/wiki/Venn_diagram), see picture below!

<img src="assets/intro_to_sets/new_union.png" width="250"/>

### b) Intersection of Two Sets 

The intersection of two sets $S$ and $T$ is the set that contains all elements of $S$ that also belong to $T$. 

Applied to our example, the intersection of $S$ and $T$ is given by {6}, so it contains the elements that are multiples of both 2 AND 3.

In mathematical terms, the intersection of $S$ and $T$ is denoted as $S \cap T$.

<img src="assets/intro_to_sets/new_intersection.png" width="250"/>

### c) Relative Complement or the Difference

If you have S and T, the relative complement of S contains all the elements of T that are NOT in S. This is also sometimes referred to as the *difference*. The difference is denoted by $ T\backslash S $ or $T-S$.

In this case, the relative complement of S (or $ T\backslash S $) is $\{2,4,8\}$. The relative complement of T (or $ S\backslash T $) is $\{3,9,12\}$.

<img src="assets/intro_to_sets/new_rel_comp.png" width="250"/>

### d) Absolute Complement

There is another definition of the complement when considering universal sets $\Omega$ as well. In this context, we're talking about the *absolute complement*.

The absolute complement of $S$, with respect to the Universal set $\Omega$, is the collection of the objects in $\Omega$ that don't belong to $S$.

Note how the definition of $\Omega$ is very important here. Imagine a set $S= \{\text{elephant, alligator, tiger, bear}\}$. The complement of this set will depend on how the universal set is defined: Is $\Omega$ equal to *the animals in the Bronx Zoo*, or *the 20 most deadly animals in the world*?

Mathematically, the absolute complement of $S$ is denoted as $S'$ or $S^c$.

Let's reconsider $S$ and $T$ as defined previously.

Let's define $\Omega$, the universal set (denoted by the box around the two Venn diagrams), as the set that contains the multiples of both 2 and 3 until 20. Then the elements of $\Omega$ are $\{2,3,4,6,8,9,10,12,14,15,16,18,20\}$. 

The absolute complement of $S$ (so, $S'$ or $S^c$) is then given by $\{2,4,8,10,14,15,16,18,20\}$.

<img src="assets/intro_to_sets/new_abs_comp.png" width="250"/>

## Inclusion-Exclusion Principle

Note that if you want to know how many elements are in set $S$ versus $T$, you can't simply sum up the elements, because they have elements in common.

In combinational mathematics, the inclusion-exclusion principle is a counting technique that solves this problem.

When having two sets, the method for counting the number of elements in the union of two finite sets is given by:

$\mid S \cup T \mid = \mid S \mid + \mid T \mid - \mid S \cap T \mid $,

where the horizontal lines denote the *cardinality* of a set, which is the number of elements in the set, considering a set with a finite number of elements. 

The formula expresses the fact that the sum of the sizes of the two sets may be too large since some elements may be counted twice. For the double-counted elements, one is subtracted again.

This formula can be extended to three sets, four sets, etc. For example, imagine you have a third set $R$. The number of elements in the union of three finite sets is given by:

$\mid S \cup T\cup R \mid = \mid S \mid + \mid T \mid + \mid R \mid - \mid S \cap T \mid  -\mid S \cap R \mid - \mid R \cap T \mid  + \mid S \cap T \cap R \mid $


<img src="assets/intro_to_sets/new_venn_diagram.png" width="350"/>

## Empty Sets

When there are no elements in a certain set, this set is **empty**, denoted by $\emptyset$ or simply $\{\}$

## Sets in Python

Some things to bear in mind when working with sets in Python:

* Sets are unordered collections of unique elements.
* Sets are iterable.
* Sets are collections of lower level python objects (just like lists or dictionaries).

Documentation for sets in Python can be found here: [Sets](https://docs.python.org/3.6/library/stdtypes.html#set-types-set-frozenset)

## Sets and Set Operations: A Summative Example

To put this all together, let's consider an example with restaurants:

Think about a *set A* with all the restaurants that serve Italian food.
Next, there is a *set B* with all the restaurants that serve burgers.

The **union** of these sets, *set C*, contains the set of restaurants that either serve Italian food, burgers or both.

You could say that the **universal set** here, *set U*, contains all the restaurants in the world (with any type of food). Then *set C* is a **subset** of *set U*. 

The **intersection** of *A* and *B* contains the restaurants that serve _both_ Italian food and burgers.

The **relative complement** of *set A* contains the restaurants that serve burgers but _not_ Italian food.

The **absolute complement** of *set A* contains the restaurants that serve *any food* but _no_ Italian food.

---

## Practice

## Exploring Set Operations Using a Venn Diagram

Let's start with a pretty conceptual example. Let's consider the following sets:

   - $\Omega$ = positive integers between [1, 12]
   - $A$= even numbers between [1, 10]
   - $B = \{3,8,11,12\}$
   - $C = \{2,3,6,8,9,11\}$
    

#### a. Illustrate all the sets in a Venn Diagram like the one below. The rectangular shape represents the universal set.

<img src="./assets/intro_to_sets_lab/venn_diagr.png" width="600">

#### b. Using your Venn Diagram, list the elements in each of the following sets:

- $ A \cap B$
- $ A \cup C$
- $A^c$ 
- The absolute complement of B
- $(A \cup B)^c$
- $B \cap C'$
- $A\backslash B$
- $C \backslash (B \backslash A)$ 
- $(C \cap A) \cup (C \backslash B)$

#### c. For the remainder of this exercise, let's  create sets A, B and C and universal set U in Python and test out the results you came up with. Sets are easy to create in Python. For a guide to the syntax, follow some of the documentation [here](https://www.w3schools.com/python/python_sets.asp)

In [ ]:
#s.add(t)  # add an element to a set

In [ ]:
# Create set A
A =  {2, 4, 6, 8, 10}
'Type A: {}, A: {}'.format(type(A), A) # "Type A: <class 'set'>, A: {2, 4, 6, 8, 10}"

"Type A: <class 'set'>, A: {2, 4, 6, 8, 10}"

In [ ]:
# Create set B
B =  {8, 11, 3, 12}
'Type B: {}, B: {}'.format(type(B), B) # "Type B: <class 'set'>, B: {8, 11, 3, 12}"

"Type B: <class 'set'>, B: {8, 3, 11, 12}"

In [ ]:
# Create set C
C =  {2, 3, 6, 8, 9, 11}
'Type C: {}, C: {}'.format(type(C), C) # "Type C: <class 'set'>, C: {2, 3, 6, 8, 9, 11}"

"Type C: <class 'set'>, C: {2, 3, 6, 8, 9, 11}"

In [ ]:
# Create universal set U
U = set([1,2,3,4,5,6,7,8,9,10,11,12])
'Type U: {}, U: {}'.format(type(U), U)
#'Type U: {}, U: {}'.format(type(U), U) # "Type U: <class 'set'>, U: {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}"

"Type U: <class 'set'>, U: {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}"

Now, verify your answers in section 1 by using the correct methods in Python. To provide a little bit of help, you can find a table with common operations on sets below.

| Method        |	Equivalent |	Result |
| ------                    | ------       | ------    |
| s.issubset(t)             |	s <= t     | test whether every element in s is in t
| s.issuperset(t)           |	s >= t     | test whether every element in t is in s
| s.union(t)                |	s $\mid$ t | new set with elements from both s and t
| s.intersection(t)         |	s & t      | new set with elements common to s and t
| s.difference(t)           |	s - t 	   | new set with elements in s but not in t
| s.symmetric_difference(t) |	s ^ t      | new set with elements in either s or t but not both

#### 1. $ A \cap B$

In [ ]:
A_inters_B =  A & B
A_inters_B

{8}

#### 2. $ A \cup C $

In [ ]:
A_union_C = A | C
A_union_C
# {2, 3, 4, 6, 8, 9, 10, 11}

{2, 3, 4, 6, 8, 9, 10, 11}

#### 3.  $A^c$ (you'll have to be a little creative here!)

In [ ]:
A_comp = U.difference(A) # or A_comp = U-A
A_comp # {1, 3, 5, 7, 9, 11, 12}

{1, 3, 5, 7, 9, 11, 12}

#### 4.  $(A \cup B)^c $

In [ ]:
A_union_B_comp = U - (A | B) 
A_union_B_comp # {1, 5, 7, 9}

{1, 5, 7, 9}

#### 5. $B \cap C' $

In [ ]:
B_inters_C_comp = B & (U-C)
B_inters_C_comp # {12}

{12}

#### 6. $A\backslash B$

In [ ]:
compl_of_B = A-B
compl_of_B # {2, 4, 6, 10}

{2, 4, 6, 10}

#### 7. $C \backslash (B \backslash A) $

In [ ]:
C_compl_B_compl_A= C-(B-A)
C_compl_B_compl_A # {2, 6, 8, 9}

{2, 6, 8, 9}

#### 8.  $(C \cap A) \cup (C \backslash B)$

In [ ]:
C_inters_A_union_C_min_B= (C&A)|(C-B)
C_inters_A_union_C_min_B # {2, 6, 8, 9}

{2, 6, 8, 9}

## The Inclusion Exclusion Principle

Use A, B and C from exercise one to verify the inclusion exclusion principle in Python. 
You can use the sets A, B and C as used in the previous exercise. 

Recall from the previous lesson that:

$$\mid A \cup B\cup C\mid = \mid A \mid + \mid B \mid + \mid C \mid - \mid A \cap B \mid  -\mid A \cap C \mid - \mid B \cap C \mid  + \mid A \cap B \cap C \mid $$

Combining these main commands:

| Method        |	Equivalent |	Result |
| ------                    | ------       | ------    |
| a.union(b)                |	A $\mid$ B | new set with elements from both a and b
| a.intersection(b)         |	A & B      | new set with elements common to a and b

along with the `len(x)` function to get to the cardinality of a given x ("|x|").

What you'll do is translate the left hand side of the equation for the inclusion principle in the object `left_hand_eq`, and the right hand side in the object `right_hand_eq` and see if the results are the same.

In [ ]:
left_hand_eq = len(A | B | C)
print(left_hand_eq)  # 9 elements in the set

9

In [ ]:
right_hand_eq = len(A)+len(B)+len(C)- len(A&B)-len(A&C)-len(B&C)+len(A&B&C)
print(right_hand_eq) # 9 elements in the set

9

In [ ]:
left_hand_eq == right_hand_eq # Use a comparison operator to compare `left_hand_eq` and `right_hand_eq`. Needs to say "True".

True

## Set Operations in Python

Mary is preparing for a road trip from her hometown, Boston, to Chicago. She has quite a few pets, yet luckily, so do her friends. They try to make sure that they take care of each other's pets while someone is away on a trip. A month ago, each respective person's pet collection was given by the following three sets:

In [ ]:
Nina = set(["Cat","Dog","Rabbit","Donkey","Parrot", "Goldfish"])
Mary = set(["Dog","Chinchilla","Horse", "Chicken"])
Eve = set(["Rabbit", "Turtle", "Goldfish"])

In this exercise, you'll be able to use the following operations:

|Operation                          |	Equivalent |	Result|
| ------                            | ------       | ------   |
|s.update(t)                        | 	$s \mid t$ 	   |return set s with elements added from t|
|s.intersection_update(t)           | 	s &= t     |	return set s keeping only elements also found in t|
|s.difference_update(t)             |	s -= t 	   |return set s after removing elements found in t|
|s.symmetric_difference_update(t)   |	s ^= t 	   |return set s with elements from s or t but not both|
|s.add(x)                           |	           |	add element x to set s|
|s.remove(x)                        |	           |	remove x from set s|
|s.discard(x)                       |	           |	removes x from set s if present|
|s.pop()                            | 	           |	remove and return an arbitrary element from s|
|s.clear()            	            |  	           |remove all elements from set s|

Sadly, Eve's turtle passed away last week. Let's update her pet list accordingly.

In [ ]:
Eve.remove("Turtle")
Eve # should be {'Rabbit', 'Goldfish'}

{'Goldfish', 'Rabbit'}

This time around, Nina promised to take care of Mary's pets while she's away. But she also wants to make sure her pets are well taken care of. As Nina is already spending a considerable amount of time taking care of her own pets, adding a few more won't make that much of a difference. Nina does want to update her list while Marie is away.

In [ ]:
Nina.update(Mary)
Nina # {'Chicken', 'Horse', 'Chinchilla', 'Parrot', 'Rabbit', 'Donkey', 'Dog', 'Cat', 'Goldfish'}

{'Cat',
 'Chicken',
 'Chinchilla',
 'Dog',
 'Donkey',
 'Goldfish',
 'Horse',
 'Parrot',
 'Rabbit'}

Mary, on the other hand, wants to clear her list altogether while away:

In [ ]:
Mary.clear()
Mary  # set()

set()

Look at how many species Nina is taking care of right now.

In [ ]:
n_species_Nina = len(Nina)
n_species_Nina  # 9

9

Taking care of this many pets is weighing heavily on Nina. She remembered Eve had a smaller collection of pets lately, and that's why she asks Eve to take care of the common species. This way, the extra pets are not a huge effort on Eve's behalf. Let's update Nina's pet collection.

In [ ]:
Nina.difference_update(Eve)
Nina # 7

{'Cat', 'Chicken', 'Chinchilla', 'Dog', 'Donkey', 'Horse', 'Parrot'}

Taking care of 7 species is something Nina feels comfortable doing!

## Writing Down the Elements in a Set


Mary dropped off her Pet's at Nina's house and finally made her way to the highway. Awesome, her vacation has begun!
She's approaching an exit. At the end of this particular highway exit, cars can either turn left (L), go straight (S) or turn right (R). It's pretty busy and there are two cars driving close to her. What you'll do now is create several sets. You won't be using Python here, it's sufficient to write the sets down on paper. A good notion of sets and subsets will help you calculate probabilities in the next lab!

Note: each set of action is what _all three cars_ are doing at any given time

a. Create a set $A$ of all possible outcomes assuming that all three cars drive in the same direction.
           
b. Create a set $B$ of all possible outcomes assuming that all three cars drive in a different direction.
             
c. Create a set $C$ of all possible outcomes assuming that exactly 2 cars turn right.
            
d. Create a set $D$ of all possible outcomes assuming that exactly 2 cars drive in the same direction.

                          
e. Write down the interpretation and give all possible outcomes for the sets denoted by:
 - I. $D'$ 
 - II. $C \cap D$, 
 - III. $C \cup D$.

In [ ]:
# a. Solution: $A = {(L,L,L); (S,S,S); (R,R,R)}$
# b. Solution: $B = {(L,R,S); (L,S,R); (R,L,S); (R,S,L); (S,L,R); (S,R,L)}$

# c. Solution: $C= {(L,R,R); (R,L,R); (R,R,L); (S,R,R); (R,S,R); (R,R,S)}$

# d. Solution: $D = {(L,R,R); (R,L,R); (R,R,L); (S,R,R); (R,S,R); (R,R,S);\ 
 #(L,S,S); (S,L,S); (S,S,L); (R,S,S); (S,R,S); (S,S,R); \ (S,L,L); (L,S,L);
 #(L,L,S); (R,L,L); (L,R,L); (L,L,R)}$

#e.

# I. $D'$: all cars go in a different direction, or all go in the same direction. 
# $D' = {(L,R,S); (L,S,R); (R,L,S); (R,S,L); (S,L,R); (S,R,L); (L,L,L); (S,S,S); (R,R,R)}$

# II. The intersection between 2 cars go right, and 2 cars go in the same direction. 
# As C is a subset of D, this boils down to C again, 
# so $C \cap D = C = {(L,R,R); (R,L,R); (R,R,L); (S,R,R); (R,S,R); (R,R,S)} $

# III. The union between 2 cars go right, and 2 cars go in the same direction. 
# So the set we end up with is the set of 2 cars going in the same direction, 
# which boils down to D again. $C \cup D = D = {(L,R,R); (R,L,R); (R,R,L); (S,R,R); 
# (R,S,R); (R,R,S);\ (L,S,S); (S,L,S); (S,S,L); (R,S,S); (S,R,S); (S,S,R);\ (S,L,L); 
# (L,S,L); (L,L,S); (R,L,L); (L,R,L); (L,L,R)}$

## Optional Exercise: European Countries

Use set operations to determine which European countries are not in the European Union. You just might have to clean the data first with pandas.

In [ ]:
import pandas as pd

#Load Europe and EU
europe = pd.read_excel('data/intro_to_sets_lab/Europe_and_EU.xlsx', sheet_name = 'Europe') 
eu = pd.read_excel('data/intro_to_sets_lab/Europe_and_EU.xlsx', sheet_name = 'EU')

#Remove any whitespace from names
europe.Country = europe.Country.map(lambda x: x.strip()) 
eu.Country = eu.Country.map(lambda x: x.strip()) #Remove any whitespace from names

In [ ]:
display(europe.head(3)) #preview dataframe
display(eu.head(3))

,Rank,Country,Population,% of population,Average relative annual growth (%),Average absolute annual growth,Estimated doubling time (Years),Official figure (where available),Date of last figure,Regional grouping,Source
0,1.0,Russia,143964709,17.15,0.19,294285,368,146839993,2017-01-01 00:00:00,EAEU,[1]
1,2.0,Germany,82521653,9.80,1.20,600000,90,82800000,2016-12-31 00:00:00,EU,Official estimate
2,3.0,Turkey,80810000,9.60,1.34,1035000,52,77695904,2016-12-31 00:00:00,NaN,[2]

,Rank,Country,2017 population,% of pop.,Average relative annual growth,Average absolute annual growth,Official figure,Date of last figure,Source
0,1,Germany,82800000,16.18,0.76,628876,82576900,2017-03-31,Official estimate
1,2,France,67210459,13.10,0.40,265557,67174000,2018-01-01,Monthly official estimate
2,3,United Kingdom,65808573,12.86,0.65,428793,65648100,2017-06-30,Official estimate

In [ ]:
set(eu.Country) < set(europe.Country)

True

In [ ]:
set(europe.Country) - set(eu.Country)

{'Albania',
 'Andorra',
 'Armenia',
 'Azerbaijan',
 'Belarus',
 'Bosnia and Herzegovina',
 'Faroe Islands (Denmark)',
 'Georgia',
 'Gibraltar (UK)',
 'Guernsey (UK)',
 'Iceland',
 'Isle of Man (UK)',
 'Jersey (UK)',
 'Kosovo',
 'Liechtenstein',
 'Macedonia',
 'Moldova',
 'Monaco',
 'Montenegro',
 'Norway',
 'Russia',
 'San Marino',
 'Serbia',
 'Svalbard (Norway)',
 'Switzerland',
 'Turkey',
 'Ukraine',
 'Vatican City',
 'Åland Islands (Finland)'}